name: Lambda Tests

# We are a reusable Workflow only
on:
  workflow_call:
    secrets:
      SLACK_WEBHOOK_URL:
        required: false

env:
    JDK_VERSION: 21
    GRADLE_VERSION: 8.7

jobs:
  tests:
    name: Tests
    runs-on: "ubuntu-latest"
    continue-on-error: false
    strategy:
      fail-fast: false
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: ${{ matrix.jdkVersion }}

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: ${{ env.GRADLE_VERSION }}

      - name: Test Lambda
        run: |
          gradle downloadBoxLang
          gradle test --stacktrace --console=plain

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: tests-${{ matrix.os }}-${{ matrix.jdkVersion }}
          path: |
            **/build/reports/tests/**
            **/build/test-results/**

  publish-test-results:
    name: Publish Test Results
    runs-on: ubuntu-latest
    needs: tests
    if: always()
    permissions:
      checks: write
      pull-requests: write
      contents: read
      issues: read
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: |
            artifacts/**/*.xml
